package io.vitess.model;

import io.vitess.constants.SysWmsStatus;
import io.vitess.enums.*;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * @author YSH4807
 * @date 2018/4/11 11:14
 */
@Data
public class CompanyShop implements Serializable {

    /**
     * PK
     */
    private Long id;

    /** appKey */
    private String appKey;
    /** appSecret */
    private String appSecret;
    /** brand */
    private String brand;
    /** bzSessionKey */
    private String bzSessionKey;
    /** company */
    private String company;
    /** createTime */
    private java.util.Date createTime;
    /** paymentType */
    private Integer paymentType;
    /** fenxiaoName */
    private String fenxiaoName;
    /** industry */
    private String industry;
    /** innerShopCode */
    private String innerShopCode;
    /** interfaceSecurityAcc */
    private String interfaceSecurityAcc;
    /** isApplySuggestedTrans */
    private Integer isApplySuggestedTrans;
    /** isApplyVmiPromotion */
    private Integer isApplyVmiPromotion;
    /** isAutoCommit */
    private Integer isAutoCommit;
    /** 是否自动过仓到仓库（O2O订单） */
    private Integer isAutoCommitToWhForO2o;
    /** isAutoFinishRa */
    private Integer isAutoFinishRa;
    /** isAutoOrder */
    private Integer isAutoOrder;
    /** isBaozunrefund */
    private Integer isBaozunrefund;
    /** isBaozunBillingInvoice */
    private Integer isBaozunBillingInvoice;
    /** isBillingInvoiceDetail */
    private Integer isBillingInvoiceDetail;
    /** isBound */
    private Integer isBound;
    /** isCancelSoAuto */
    private Integer isCancelSoAuto;
    /** isCommitSuccessively */
    private Integer isCommitSuccessively;
    /** isDefaultInvoice */
    private Integer isDefaultInvoice;
    /** isDefaultLandTrans */
    private Integer isDefaultLandTrans;
    /** isForbidOffline */
    private Integer isForbidOffline;
    /** isIgnoreMemo */
    private Integer isIgnoreMemo;
    /** isMqInv */
    private Integer isMqInv;
    /** isMqLogistics */
    private Integer isMqLogistics;
    /** isMqMdPrice */
    private Integer isMqMdPrice;
    /** isMqOrder */
    private Integer isMqOrder;
    /** isMqSale */
    private Integer isMqSale;
    /** isMqSku */
    private Integer isMqSku;
    /** isMqSkuPrice */
    private Integer isMqSkuPrice;
    /** isMqSo */
    private Integer isMqSo;
    /** isMqSoResult */
    private Integer isMqSoResult;
    /** isO2oShop */
    private Integer isO2oShop;
    /** isOnSalesSku */
    private Integer isOnSalesSku;
    /** isOpenSyncInv */
    private Integer isOpenSyncInv;
    /** isOpenedWlb */
    private Integer isOpenedWlb;
    /** isOpenedApi */
    private Boolean isOpenedApi;
    /** isOwnWms */
    private Integer isOwnWms;
    /** isRequiredTrans */
    private Integer isRequiredTrans;
    /** isSms */
    private Integer isSms;
    /** isSplitByType */
    private Boolean isSplitByType;
    /** isSyncInventory */
    private Boolean isSyncInventory;
    /** isSyncManualUploadSku */
    private Integer isSyncManualUploadSku;
    /** isSyncMqsoresultAlone */
    private Integer isSyncMqsoresultAlone;
    /** isSyncPartlyDf */
    private Integer isSyncPartlyDf;
    /** isSysFinish */
    private Integer isSysFinish;
    /** lifeCycleStatus */
    private Integer lifeCycleStatus;
    /** mail */
    private String mail;
    /** managerMode */
    private Integer managerMode;
    /** memberName */
    private String memberName;
    /** mobile */
    private String mobile;
    /** mqAsnReceive */
    private String mqAsnReceive;
    /** mqFeedback */
    private String mqFeedback;
    /** mqIncInventory */
    private String mqIncInventory;
    /** mqInventory */
    private String mqInventory;
    /** mqLogistics */
    private String mqLogistics;
    /** mqMdPrice */
    private String mqMdPrice;
    /** mqName */
    private String mqName;
    /** mqNotify */
    private String mqNotify;
    /** mqOrder */
    private String mqOrder;
    /** mqPrice */
    private String mqPrice;
    /** mqRtv */
    private String mqRtv;
    /** mqSale */
    private String mqSale;
    /** mqSku */
    private String mqSku;
    /** mqSo */
    private String mqSo;
    /** openDate */
    private java.util.Date openDate;
    /** printShopName */
    private String printShopName;
    /** rtnWarehouseAddress */
    private String rtnWarehouseAddress;
    /** sessionKey */
    private String sessionKey;
    /** settlementMode */
    private Integer settlementMode;
    /** shopId */
    private String shopId;
    /** shopName */
    private String shopName;
    /** 销售模式，半角逗号分隔 */
    private String salesModes;
    /** soCodePrefix */
    private String soCodePrefix;
    /** source */
    private String source;
    /** telephone */
    private String telephone;
    /** transRegionApplyType */
    private Integer transRegionApplyType;
    /** version */
    private Integer version;
    /** vmiCode */
    private String vmiCode;
    /** vmiWhSource */
    private String vmiWhSource;
    /** whModel */
    private Integer whModel;
    /** zipcode */
    private String zipcode;
    /** ouId */
    private Long ouId;
    /** 是否自动拆单 */
    private Integer isAutoSplitOrder;
    /** 是否验证英文地址 */
    private Integer needVerifyEnAddress;
    /** 是否自动创建退款 */
    private Integer isAutoCreateRf;
    /** 是否需要同步数据至 */
    private Integer isSyncToOms;
    /** OMS物流模板 */
    private Long deftemId;
    /** isUseDeftrans */
    private Integer isUseDeftrans;
    /** isOpenCloudStack */
    private Integer isOpenCloudStack;
    /** 拆分类目, 1:按店铺SKU默认仓拆分订单, 2:不拆分 */
    private Integer skuSplitType;
    /** 是否应用含特殊商品挂起 */
    private Integer isSuspendForSpecialSku;
    /** 默认发票抬头类型 */
    private Integer defInvoiceTitleType;
    /** 是否解析订单服务信息 */
    private Integer isParseOrderServiceInfo;
    /** 平台店铺编码 */
    private String platformShopCode;
    /** 店铺销售区域 */
    private String businessRegionType;
    /** 是否开启依次过仓逻辑 */
    private Integer isOpenSeqToWh;
    /** 卖家收货地址编号 */
    private Long sellerAddressId;
    /** 是否使用淘宝退款指令  */
    private Integer isRefundDirect;
    /** 是否创建 电子凭证订单  */
    private Integer isCreateEticket;
    /** 是否开启数据分析 */
    private Integer isOpenDataAnalysis;
    /** 是否抓起未付款订单 */
    private Integer isParseNoPayOrder;
    /** isOpenDirectWms */
    private Integer isOpenDirectWms;
    /** 店铺code(pacs/wms/tmalloms交互使用) */
    private String interfaceShopCode;
    /** 是否允许分仓发货 */
    private Integer isAllowDs;
    /** 公司名称 */
    private String companyName;
    /** 固定经营项目名称 */
    private String fixedOperatingItem;
    /** 自动拆票类型：1.按单张发票最大开票金额及备注长度拆票；2.不支持拆票 */
    private Integer autoSplitType;
    /** 开票金额计算规则：1.只体现商品信息(扣除积分和折扣);2.发票明细包含两部分：商品明细、积分和拆扣明细 */
    private Integer invoiceAmtRule;
    /** 单张发票最大开票金额(如果不配置,则默认是 10000) */
    private java.math.BigDecimal maxInvoiceAmt;
    /** 是否开启拆单发送短信功能 */
    private Integer isOpenSplitOrderSendSms;
    /** 是否是只做数据分析的店铺 */
    private Integer isDaShop;
    /** isSpecificShopToEdw */
    private Integer isSpecificShopToEdw;
    /** 是否创建自动发货订单 */
    private Integer isCreateAutoDelivery;
    /** 销售模式 */
    private Integer salesMode;
    /** 仓储客户代码 */
    private String whCustomerCode;
    /** 是否开启订单行销售模式打标 */
    private Boolean isApplySalesMode;
    /** 店铺平台类型 */
    private String platformType;
    /** 发票形式：false 纸质发票；true 电子发票 */
    private Boolean invoiceKind;
    /** 是否菜鸟仓发货 */
    private Boolean isCaiNiao;
    /** 店铺是否开启库存共享 */
    private Boolean isShareInventory;
    /** 货主编码 */
    private String ownerCode;
    /** 省 */
    private String province;
    /** 市 */
    private String city;
    /** 详细地址 */
    private String address;
    /** 区 */
    private String district;
    /** 是否支持一键拆单 */
    private Integer isSurportOnekeySplit;
    /** 一键拆单上限数 */
    private Integer onekeySplitUpperbound;
    /** installCompanyName */
    private String installCompanyName;
    /** 0 不开启（默认） 1 开启。开启后取消订单时必须填写取消原因 */
    private Integer isNeedReason;
    /** 是否开启订单路由默认否 */
    private Integer isOrderRoute;
    /** 客户编码 */
    private String customerCode;
    /** 门店ID或者EC仓名字 */
    private Boolean isOmnichannelParam;
    /** 是否开启应用退款审核规则 */
    private Integer isApplyAuditRule;
    /** 行业名称 */
    private String industryName;
    /** 发送订单路由的店铺唯一CODE */
    private String code;
    /** Tommy定制，是否开启商品类型配置0：禁止  1：开启 */
    private Integer isOpenSkuType;
    /** isHangByAbroadOrder */
    private Integer isHangByAbroadOrder;
    /** 是否开启依次过仓 */
    private Boolean isOneByOneToWh;
    /** 开启ag退款 */
    private Boolean openAgRefund;
    /** 是否开启配送方式拆单 */
    private Boolean isShippingMethods;
    /** LF仓对接有区域要求，定义和LF对接的物流商开关 */
    private Boolean isTrans;
    /** 是否开启预售 */
    private Integer isPresale;
    /** 是否开启预包装 */
    private Integer isPrepackage;
    /** 运单号必填 */
    private Integer isTrackingNo;
    /** LF仓对接有区域要求，定义和LF对接的物流商开关 */
    private Boolean isOpenMq;
    /** 一个平台对接码根据逻辑库位同步多份库存到平台 */
    private Integer isMultiSku;
    /** 是否支持换转退 */
    private Integer isTradeToReturn;
    /** 是否退换货并行 */
    private Integer isParallel;
    /** 退货入库配置 */
    private Integer raInboundConfig;
    /** 指定店铺入库配置项 */
    private String raInboundChannelCode;
    /** 换货是否扣减平台库存 */
    private Integer isChgPlatformIvt;
    /** agSecond */
    private Integer agSecond;
    /** 同步库存后是否查询验证天猫的库存 */
    private Integer isQueryInv;
    /** 同步库存是否全量转增量 */
    private Integer isOver2step;
    /** 分销店铺id,只当其分销店铺的订单被当做本店铺订单拉入oms的时候设置值!! */
    private Long fenxiaoShopCode;
    /** isRaSms */
    private Integer isRaSms;
    /** 是否开放送货上门并安装服务,如果不是1,将不能创建此项服务行 */
    private Integer isOpenDeliveryAndInstallService;
    /** 店铺是否加密（1加密，0未加密） */
    private Integer isEncrypt;
    /** 店铺加密类型- 0:直销; 1:分销; 2经销 */
    private Integer encryptType;
    /** agOpenAutoRefund */
    private Integer agOpenAutoRefund;
    /** 是否开启平台线上换货（对接AG四期，天猫换货对接） */
    private Integer isOpenOnlineExchange;
    /** 是否开启奇门 */
    private Integer isQimen;
    /** 是否开启奇门 */
    private Integer isOpenQimen;
    /** 作废换货单时是否要求填写作废原因 */
    private Integer isInvalidExchangeReason;
    /** 是否开启3.0换货过仓入库单和出库单分开推送 */
    private Integer isOpenPushTogether;
    /** 最后拉取换货指令的时间 */
    private java.util.Date lastPullExchangeDirectTime;
    /** 一次拉取换货的时间间隔(单位分钟) */
    private Integer increaseMinutes;
    /** 是否允许对这个店铺的物流宝订单应用自动拆单规则 */
    private Integer isAutoSplitOrderRuleForWlb;
    /** 是否直连OMS(意思是 TOMS销售退换货过仓对应的下位系统是否是一个OMS系统而不是WMS) */
    private Integer isDirectOms;
    //columns END
}
